2021-02-05 13:51:01,332:DEBUG:certbot._internal.main:certbot version: 1.12.0
2021-02-05 13:51:01,333:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2021-02-05 13:51:01,333:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/certbot', '--email', 'vyacheslav25sl@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'arhproject.h1n.ru', '-d', 'www.arhproject.h1n.ru']
2021-02-05 13:51:01,334:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-02-05 13:51:01,403:DEBUG:certbot._internal.log:Root logging level set at 20
2021-02-05 13:51:01,404:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-02-05 13:51:01,407:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2021-02-05 13:51:01,422:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fc7b01af3a0>
Prep: True
2021-02-05 13:51:01,424:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fc7b01af3a0> and installer None
2021-02-05 13:51:01,424:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2021-02-05 13:51:01,436:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/111767649', new_authzr_uri=None, terms_of_service=None), 846def15d2378286355ee83a0a8c57ad, Meta(creation_dt=datetime.datetime(2021, 2, 5, 12, 26, 38, tzinfo=<UTC>), creation_host='fddfa398e1cf', register_to_eff=None))>
2021-02-05 13:51:01,439:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-02-05 13:51:01,444:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-02-05 13:51:02,258:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-02-05 13:51:02,261:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 05 Feb 2021 13:51:02 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "QqVUmce7udc": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2021-02-05 13:51:02,364:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer <certbot._internal.cli.cli_utils._Default object at 0x7fc7b023b700>
2021-02-05 13:51:02,378:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
2021-02-05 13:51:02,620:DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
2021-02-05 13:51:02,630:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/archive/arhproject.h1n.ru/cert1.pem is signed by the certificate's issuer.
2021-02-05 13:51:02,653:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/archive/arhproject.h1n.ru/cert1.pem is: OCSPCertStatus.GOOD
2021-02-05 13:51:02,665:INFO:certbot._internal.renewal:Cert not yet due for renewal
2021-02-05 13:51:02,667:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1413, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1286, in certonly
    should_get_cert, lineage = _find_cert(config, domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 331, in _find_cert
    action, lineage = _find_lineage_for_domains_and_certname(config, domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 363, in _find_lineage_for_domains_and_certname
    return _find_lineage_for_domains(config, domains)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 307, in _find_lineage_for_domains
    return _handle_identical_cert_request(config, ident_names_cert)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 259, in _handle_identical_cert_request
    response = display.menu(question, choices,
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 187, in menu
    code, selection = self._get_valid_int_ans(len(choices))
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 445, in _get_valid_int_ans
    ans = input_with_timeout(input_msg)
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 97, in input_with_timeout
    raise EOFError
EOFError
2021-02-05 13:51:02,670:ERROR:certbot._internal.log:An unexpected error occurred:
2021-02-05 13:51:02,671:ERROR:certbot._internal.log:EOFError
